### ISSUE TITLE
三个分类必须分开运行 ‘scrapy crawl zzw’

### ISSUE THREAD

**Issue by uiue** [hailong0707-zz/spider_news_all#1]
你好，三个分类必须分开运行 ‘scrapy crawl zzw’是什么意思？运行三次scrapy crawl zzw吗？

**Comment by hailong0707-zz** [comment]
@uiue 意思是，在spider_news_all/spider_news_all/spiders/zzw.py中，`start_urls`只能是以下3个中的一个，需要分别注释掉其他两个运行`scrapy crawl zzw`，一共需要运行三次。

```
'http://www.cs.com.cn/xwzx/hg/index.html',
# 'http://www.cs.com.cn/xwzx/cj/index.html',
# 'http://www.cs.com.cn/ssgs/gsxw/index.html',
```
